"""Service layer utilities for external integrations."""

from .minio import ensure_buckets, get_minio_client, get_minio_client_external
from .storage import (
    DeletionReport,
    DirectDeletionError,
    RelocationError,
    RelocationReport,
    RestorationError,
    TrashDeletionError,
    TrashEntry,
    TrashEntryNotFoundError,
    TrashRetentionError,
    UploadConflictError,
    UploadError,
    delete_prefix_directly,
    delete_prefix_from_trash,
    ensure_version_target,
    extract_manifest_version,
    list_objects_tree,
    list_trash_entries,
    move_prefix_to_trash,
    restore_prefix_from_trash,
    upload_app_archive,
    upload_book_archive,
)

__all__ = [
    "get_minio_client",
    "get_minio_client_external",
    "ensure_buckets",
    "upload_book_archive",
    "upload_app_archive",
    "list_objects_tree",
    "extract_manifest_version",
    "ensure_version_target",
    "UploadError",
    "UploadConflictError",
    "move_prefix_to_trash",
    "delete_prefix_directly",
    "DirectDeletionError",
    "RelocationError",
    "RelocationReport",
    "RestorationError",
    "DeletionReport",
    "TrashDeletionError",
    "TrashRetentionError",
    "TrashEntryNotFoundError",
    "TrashEntry",
    "list_trash_entries",
    "restore_prefix_from_trash",
    "delete_prefix_from_trash",
]
